### PR TITLE
support Conv3d, batch_norm, Upsample, add warnings for DLL load

### PR DESCRIPTION
**Pull request by ppaanngggg**
add converter for Conv3d, and pass the test:

`python -m torch2trt.test --name=Conv3d`

| Name | Data Type | Input Shapes | torch2trt kwargs | Max Error | Throughput (PyTorch) | Throughput (TensorRT) | Latency (PyTorch) | Latency (TensorRT) |
|------|-----------|--------------|------------------|-----------|----------------------|-----------------------|-------------------|--------------------|
| torch2trt.converters.Conv3d.test_Conv3d_basic | float32 | [(1, 10, 128, 128, 128)] | {} | 0.00E+00 | 37.3 | 33.1 | 26.6 | 30.3 |
| torch2trt.converters.Conv3d.test_Conv3d_stride2 | float32 | [(1, 10, 128, 128, 128)] | {} | 0.00E+00 | 295 | 263 | 3.44 | 3.86 |
| torch2trt.converters.Conv3d.test_Conv3d_kernel3 | float32 | [(1, 10, 128, 128, 128)] | {} | 2.26E-06 | 46.9 | 28.6 | 21.6 | 35 |
| torch2trt.converters.Conv3d.test_Conv3d_dilation2 | float32 | [(1, 10, 128, 128, 128)] | {} | 0.00E+00 | 3.71 | 3.7 | 271 | 271 |

`python -m torch2trt.test --name=batch_norm`

| Name | Data Type | Input Shapes | torch2trt kwargs | Max Error | Throughput (PyTorch) | Throughput (TensorRT) | Latency (PyTorch) | Latency (TensorRT) |
|------|-----------|--------------|------------------|-----------|----------------------|-----------------------|-------------------|--------------------|
| torch2trt.converters.batch_norm.test_batch_norm_1d | float32 | [(1, 10, 5)] | {} | 1.19E-07 | 1.57e+04 | 7.33e+03 | 0.0953 | 0.149 |
| torch2trt.converters.batch_norm.test_batch_norm_2d | float32 | [(1, 10, 5, 5)] | {} | 2.38E-07 | 3.09e+04 | 2.02e+04 | 0.0448 | 0.0565 |
| torch2trt.converters.batch_norm.test_batch_norm_3d | float32 | [(1, 10, 5, 5, 5)] | {} | 2.38E-07 | 3.41e+04 | 1.97e+04 | 0.0477 | 0.0626 |

`python -m torch2trt.test --name=Upsample`

| Name | Data Type | Input Shapes | torch2trt kwargs | Max Error | Throughput (PyTorch) | Throughput (TensorRT) | Latency (PyTorch) | Latency (TensorRT) |
|------|-----------|--------------|------------------|-----------|----------------------|-----------------------|-------------------|--------------------|
| torch2trt.converters.Upsample.test_Upsample_1d_size | float32 | [(1, 32, 64)] | {} | 0.00E+00 | 4.63e+04 | 2.16e+04 | 0.0364 | 0.0553 |
| torch2trt.converters.Upsample.test_Upsample_1d_size_linear | float32 | [(1, 32, 64)] | {} | 2.38E-07 | 2.44e+04 | 1.85e+04 | 0.0754 | 0.0575 |
| torch2trt.converters.Upsample.test_Upsample_1d_scale | float32 | [(1, 32, 64)] | {} | 0.00E+00 | 1.58e+04 | 7.43e+03 | 0.12 | 0.162 |
| torch2trt.converters.Upsample.test_Upsample_1d_scale_linear | float32 | [(1, 32, 64)] | {} | 2.38E-07 | 2.2e+04 | 1.22e+04 | 0.137 | 0.109 |
| torch2trt.converters.Upsample.test_Upsample_2d_size | float32 | [(1, 32, 64, 128)] | {} | 0.00E+00 | 2.55e+03 | 968 | 0.411 | 0.988 |
| torch2trt.converters.Upsample.test_Upsample_2d_size_linear | float32 | [(1, 32, 64, 128)] | {} | 4.26E-05 | 3.32e+03 | 1.04e+03 | 0.323 | 0.951 |
| torch2trt.converters.Upsample.test_Upsample_2d_scale | float32 | [(1, 32, 64, 128)] | {} | 0.00E+00 | 2.93e+03 | 1.1e+03 | 0.369 | 0.916 |
| torch2trt.converters.Upsample.test_Upsample_2d_scale_linear | float32 | [(1, 32, 64, 128)] | {} | 4.03E-05 | 3.49e+03 | 1.24e+03 | 0.314 | 0.857 |
| torch2trt.converters.Upsample.test_Upsample_3d_size | float32 | [(1, 16, 32, 64, 64)] | {} | 0.00E+00 | 53.5 | 102 | 18.8 | 10.1 |
| torch2trt.converters.Upsample.test_Upsample_3d_size_linear | float32 | [(1, 16, 32, 64, 64)] | {} | 7.15E-07 | 165 | 101 | 5.72 | 9.61 |
| torch2trt.converters.Upsample.test_Upsample_3d_scale | float32 | [(1, 16, 32, 64, 64)] | {} | 0.00E+00 | 57.6 | 111 | 17.4 | 9.15 |
| torch2trt.converters.Upsample.test_Upsample_3d_scale_linear | float32 | [(1, 16, 32, 64, 64)] | {} | 2.22E-05 | 178 | 108 | 5.33 | 8.91 |

### CODE REVIEW

**Comment by jaybdub** [comment]
Hi ppaanngggg,

Thanks for the contribution :)  I look forward to validating these changes soon.

Best,
John

**Comment by ppaanngggg** [comment]
Great! I will add test result for batch_norm. 

And I think we can delete the old batchnorm1d and batchnorm2d now.

**Comment by xdhhh** [comment]
Hi, why the latency is increased after using tensorrt for Conv3d?

**Comment by ppaanngggg** [comment]
> Hi, why the latency is increased after using tensorrt for Conv3d?

I don't know. I asked NVIDIA engineer, no answer now.

**Comment by MaratZakirov** [comment]
Hi all it is seems that batch norm doesn't work properly... :(

**Comment by Nioolek** [comment]
Hello, why I use the 3D batch_norm,I meet the error:
[TensorRT] ERROR: Parameter check failed at: ../builder/Network.cpp::addScaleNd::737, condition: nbSpatialDims == 2 || nbSpatialDims == 3
Traceback (most recent call last):
  File "convert_model_trt.py", line 221, in <module>
    model_trt = torch2trt(model, [x])
  File "/home/ubuntu/miniconda2/envs/pytorch_10.0/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 377, in torch2trt
    outputs = module(*inputs)
  File "/home/ubuntu/miniconda2/envs/pytorch_10.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/work3/code/mouse_detect/Efficient-3DCNNs-master/models/resnet.py", line 190, in forward
    x = self.layer1(x)
  File "/home/ubuntu/miniconda2/envs/pytorch_10.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/miniconda2/envs/pytorch_10.0/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/ubuntu/miniconda2/envs/pytorch_10.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/work3/code/mouse_detect/Efficient-3DCNNs-master/models/resnet.py", line 57, in forward
    out = self.bn1(out)
  File "/home/ubuntu/miniconda2/envs/pytorch_10.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/miniconda2/envs/pytorch_10.0/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 81, in forward
    exponential_average_factor, self.eps)
  File "/home/ubuntu/miniconda2/envs/pytorch_10.0/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 202, in wrapper
    converter['converter'](ctx)
  File "/home/ubuntu/miniconda2/envs/pytorch_10.0/lib/python3.7/site-packages/torch2trt/converters/batch_norm.py", line 27, in convert_batch_norm
    output._trt = layer.get_output(0)
AttributeError: 'NoneType' object has no attribute 'get_output'

How to solve it?

environment:
CUDA 10.0
CUDNN 7.0.0.11
TENSORRT 7.0
PYTORCH 1.2.0
python 3.7.0

**Pull request closed without merging**
