### PR TITLE
Adds a way to specify custom library locations and remove build artifacts

### PR DESCRIPTION
**Pull request by narendasan**
Adds a way to specify custom library locations and remove build artifacts

adds `setup.py install` subcommands `--cuda-dir=`
`--trt-inc-dir=` `--trt-lib-dir=` `--torch-dir=`

adds a `setup.py clean` which will delete generated files

moves `--plugin` into a custom install command with the other install
subcommands

Adds a -std=c++11 flag to the compile step (was hitting errors when
trying to compile plugins)

Let me know if I wrote in any poor assumptions or something.

### CODE REVIEW

**Comment by jaybdub** [comment]
Thanks @narendasan!

These look like valuable contributions towards making the project more portable.

I will verify the changes, ASAP. 

Best,
John

**Comment by mli0603** [comment]
Hi @narendasan and @jaybdub

Thanks for the fix! When I used your build.py and everything builds without error. However, when I run the test file with `python3 -m torch2trt.test --name=interpolate`, it gave me the following error.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/deepsight3/Downloads/torch2trt/torch2trt/__init__.py", line 1, in <module>
    from .torch2trt import *
  File "/home/deepsight3/Downloads/torch2trt/torch2trt/torch2trt.py", line 2, in <module>
    import tensorrt as trt
  File "/usr/local/lib/python3.5/dist-packages/tensorrt/__init__.py", line 1, in <module>
    from .tensorrt import *
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
deepsight3@deepsight3-Precision-Tower-5810:~/Downloads/torch2trt$ python3 -m torch2trt.test --name=interpolate
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/deepsight3/Downloads/torch2trt/torch2trt/test.py", line 100, in <module>
    max_error, fps, fps_trt, ms, ms_trt = run(test)
  File "/home/deepsight3/Downloads/torch2trt/torch2trt/test.py", line 25, in run
    module_trt = torch2trt(module, inputs, **self.torch2trt_kwargs)
  File "/home/deepsight3/Downloads/torch2trt/torch2trt/torch2trt.py", line 252, in torch2trt
    outputs = module(*inputs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/deepsight3/Downloads/torch2trt/torch2trt/converters/interpolate/interpolate.py", line 49, in forward
    return F.interpolate(x, self.size, mode=self.mode, align_corners=self.align_corners)
  File "/home/deepsight3/Downloads/torch2trt/torch2trt/torch2trt.py", line 97, in wrapper
    converter(ctx)
  File "/home/deepsight3/Downloads/torch2trt/torch2trt/converters/interpolate/interpolate.py", line 34, in convert_interpolate
    plugin = get_interpolate_plugin(size=size, mode=mode, align_corners=align_corners)
  File "/home/deepsight3/Downloads/torch2trt/torch2trt/converters/interpolate/interpolate.py", line 11, in get_interpolate_plugin
    creator = [c for c in registry.plugin_creator_list if c.name == PLUGIN_NAME and c.plugin_namespace == 'torch2trt'][0]
IndexError: list index out of range
```
I believe this is the same problem with #20 and #17. I am using protobuf 3.9.1, torch 1.2.0, tensorrt 5.1.5.0 and cuda 10.0. The build command i used was `sudo python3 setup.py install --plugins --cuda-dir=/usr/local/cuda-10.0/ --trt-inc-dir=/usr/lib/TensorRT-5.1.5.0/include --trt-lib-dir=/usr/lib/TensorRT-5.1.5.0/lib --torch-dir=/usr/local/lib/python3.5/dist-packages/torch`

```
running install
Building in plugin support
[4/4] g++ -shared -o torch2trt/libtorch2trt.so interpolate....gpu -lprotobuf -lprotobuf-lite -pthread -lpthread -lnvinfer
running build
running build_py
creating build
creating build/lib
creating build/lib/torch2trt
copying torch2trt/__init__.py -> build/lib/torch2trt
copying torch2trt/module_test.py -> build/lib/torch2trt
copying torch2trt/test.py -> build/lib/torch2trt
copying torch2trt/torch2trt.py -> build/lib/torch2trt
creating build/lib/torch2trt/converters
copying torch2trt/converters/relu.py -> build/lib/torch2trt/converters
copying torch2trt/converters/AdaptiveAvgPool2d.py -> build/lib/torch2trt/converters
copying torch2trt/converters/Identity.py -> build/lib/torch2trt/converters
copying torch2trt/converters/Conv2d.py -> build/lib/torch2trt/converters
copying torch2trt/converters/ReLU.py -> build/lib/torch2trt/converters
copying torch2trt/converters/ReLU6.py -> build/lib/torch2trt/converters
copying torch2trt/converters/MaxPool2d.py -> build/lib/torch2trt/converters
copying torch2trt/converters/ConvTranspose2d.py -> build/lib/torch2trt/converters
copying torch2trt/converters/iadd.py -> build/lib/torch2trt/converters
copying torch2trt/converters/identity.py -> build/lib/torch2trt/converters
copying torch2trt/converters/__init__.py -> build/lib/torch2trt/converters
copying torch2trt/converters/adaptive_avg_pool2d.py -> build/lib/torch2trt/converters
copying torch2trt/converters/transpose.py -> build/lib/torch2trt/converters
copying torch2trt/converters/view.py -> build/lib/torch2trt/converters
copying torch2trt/converters/relu6.py -> build/lib/torch2trt/converters
copying torch2trt/converters/BatchNorm2d.py -> build/lib/torch2trt/converters
copying torch2trt/converters/mean.py -> build/lib/torch2trt/converters
copying torch2trt/converters/Linear.py -> build/lib/torch2trt/converters
copying torch2trt/converters/add.py -> build/lib/torch2trt/converters
copying torch2trt/converters/cat.py -> build/lib/torch2trt/converters
copying torch2trt/converters/LogSoftmax.py -> build/lib/torch2trt/converters
copying torch2trt/converters/AvgPool2d.py -> build/lib/torch2trt/converters
creating build/lib/torch2trt/converters/interpolate
copying torch2trt/converters/interpolate/interpolate.py -> build/lib/torch2trt/converters/interpolate
copying torch2trt/converters/interpolate/__init__.py -> build/lib/torch2trt/converters/interpolate
copying torch2trt/converters/interpolate/interpolate_pb2.py -> build/lib/torch2trt/converters/interpolate
copying torch2trt/libtorch2trt.so -> build/lib/torch2trt
running install_lib
copying build/lib/torch2trt/libtorch2trt.so -> /usr/local/lib/python3.5/dist-packages/torch2trt
copying build/lib/torch2trt/converters/interpolate/interpolate_pb2.py -> /usr/local/lib/python3.5/dist-packages/torch2trt/converters/interpolate
byte-compiling /usr/local/lib/python3.5/dist-packages/torch2trt/converters/interpolate/interpolate_pb2.py to interpolate_pb2.cpython-35.pyc
running install_egg_info
running egg_info
writing top-level names to torch2trt.egg-info/top_level.txt
writing torch2trt.egg-info/PKG-INFO
writing dependency_links to torch2trt.egg-info/dependency_links.txt
reading manifest file 'torch2trt.egg-info/SOURCES.txt'
writing manifest file 'torch2trt.egg-info/SOURCES.txt'
removing '/usr/local/lib/python3.5/dist-packages/torch2trt-0.0.0-py3.5.egg-info' (and everything under it)
Copying torch2trt.egg-info to /usr/local/lib/python3.5/dist-packages/torch2trt-0.0.0-py3.5.egg-info
running install_scripts
```

I can see  interpolate being built, but somehow it is not in the CONVERTERS of torch2trt. Can you help? Thank you very much!

**Comment by jaybdub** [comment]
Just merged into master.  Sorry for delay.

Thank you @narendasan !

@mli0603 The error was likely caused by caffe2 linking error when using PyTorch 1.2.  This should be fixed now.

Best,
John

**Comment by adizhol** [comment]
@jaybdub 
I'm having the same issue as @mli0603, using PyTorch 1.2, TensortRT 7, CUDA 10.2, python 3.6
Any ideas?

**Pull request merged**
