### PR TITLE
Additional converters for floordiv, mod, ne, and torch::tensor() operations

### PR DESCRIPTION
**Pull request by meremeev**

### CODE REVIEW

**Comment by jaybdub** [comment]
Hi @meremeev,

Thanks for this pull request!  I took a quick glance, this looks nice!

I look forward to testing these features and getting back.

Out of curiosity, were these additions inspired by a particular use case / model?  If so I'm interested to hear what this might be to better understand how you're using (or hoping to use) torch2trt.

Best,
John

**Comment by jaybdub** [comment]
Hi @meremeev ,

I've tested the changes, they seem to work well, and other functions are behaving as expected.

I think this is good to merge.  I would only suggest that we add entries to the [CHANGELOG](https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/CHANGELOG.md) under master just to help establish the practice in this project.

https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/CHANGELOG.md

Let me know if you're interested in adding the entries.  Otherwise, I'm happy to add them.

Best,
John

**Comment by meremeev** [comment]
Hi John,

At Luminar we are considering using torch2trt package to convert our semantic segmentation model to TensorRT engine.. These converters are what we need to make it working. 

I will update CHANGELOG.md shortly. 

Thank you,
Mark

**Comment by meremeev** [comment]
Done

**Comment by jaybdub** [comment]
Looks great @meremeev, thanks!  Will merge this now.

Please feel free to reach out with any other issues / pull request / general discussion , etc.

Thanks again,
John

**Pull request merged**
